### ISSUE TITLE
[CHORE] Setup Theme in TailwindCSS

### ISSUE THREAD

**Issue by CyrilOlanolan** [CyrilOlanolan/bluesight#1]
The project is using TailwindCSS and we can extend the current configuration to use our own set of theme structure using the design tokens defined in Figma

**Comment by realjero** [comment]
Hello, I'm checking if this issue remains unresolved. I'm well-versed in tailwind configuration and I'm interested in incorporating your color palette. To proceed, could you please share the specific colors for background, foreground, primary, secondary, accent, destructive, muted, ...? Additionally, I'd like to inquire whether you prefer multiple shades of these colors, such as "text-primary-200".

**Comment by CyrilOlanolan** [comment]
Commit 4b1bff3 merged to main
